version: '3'
services:
  app:
    container_name: app  
    build: ./docker/app
    volumes:
      - .:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    restart: always
    networks:
      - test_db
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 8000:80 
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    restart: always
    networks:
      - test_db

networks:
  test_db:
    external: true
